inherit_from: .rubocop_todo.yml
Style/Encoding:
  Enabled: false
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Naming/MethodName:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/MethodLength:
  Max: 30
